#!/bin/bash

# Function to update system
update_system() {
    sudo dnf upgrade -y && \
    sudo mise self-update 
}

# Function to show tools
list-pkgs() {
  echo "----------------------------------------------------------------------"
  echo "-- Extra Dnf Packages"
  echo "----------------------------------------------------------------------"
  # Define base packages to filter out
  NATIVE_HIDE_LIST=(
    bash
    bind-utils
    coreutils
    dnf5
    fedora
    filesystem
    gawk
    glibc-minimal-langpack
    gettext
    gzip
    hostname
    less
    libicu
    iproute
    iputils
    ncurses
    openssl
    procps-ng
    psmisc
    rpm
    shadow-utils
    sudo
    systemd-standalone-sysusers
    tar
    tini
    util-linux
    wget
    which
    zsh-
  )

  # Convert array to regex for awk
  FILTER_REGEX=$(IFS="|"; echo "${NATIVE_HIDE_LIST[*]}")

  {
      printf "\e[1;36mPackage\tVersion\e[0m\n"
      dnf repoquery --userinstalled --qf $'%{name}\t%{version}\n' | sort
  } | column -t -s $'\t' | awk -v f="$FILTER_REGEX" '
  NR==1 {print; next}
  $1 !~ f { printf "%-30s %s\n", $1, $2 }'

  echo "----------------------------------------------------------------------"
  echo "-- Mise Packages"
  echo "----------------------------------------------------------------------"
  mise ls
}

# Function to display help
show_help() {
    echo "Usage: $1 [OPTION]"
    echo
    echo "Options:"
    echo "  --update       Update system packages including mise"
    echo "  --list-pkgs    List available packages & tools"
    echo "  --help         Show this help message and exit"
    echo
    exit 0
}

# Check for arguments
if [ $# -eq 0 ]; then
  show_help
fi

# Map options to functions
case "$1" in
    --update)
        update_system
        ;;
    --list-pkgs)
        list-pkgs
        ;;
    --help)
        show_help
        ;;
    *)
        echo "Unknown option: $1"
        echo "Use --help for usage information."
        exit 1
        ;;
esac
